CREATE TABLE users(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50)  NOT NULL);

CREATE TABLE events(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,
    event_date        TIMESTAMP WITH TIME ZONE NOT NULL,
    location          VARCHAR(255) NOT NULL,
    total_tickets     INTEGER NOT NULL,
    available_tickets INTEGER NOT NULL,
    ticket_price      DECIMAL(10, 2) NOT NULL,

    CONSTRAINT chk_total_tickets
    CHECK (total_tickets > 0),

    CONSTRAINT chk_available_tickets
    CHECK (available_tickets >= 0 AND available_tickets <= total_tickets),

    CONSTRAINT chk_ticket_price
    CHECK (ticket_price >= 0));

CREATE TABLE tickets(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id      BIGINT NOT NULL,
    user_id       BIGINT NOT NULL,
    purchase_time TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_ticket_event
    FOREIGN KEY (event_id)
    REFERENCES events (id),

    CONSTRAINT fk_ticket_user
    FOREIGN KEY (user_id)
    REFERENCES users (id));