### Login
### Expected: 200 OK + JWT
### ------------------------------------------------------------
POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
  "username": "user",
  "password": "user123"
}

> {%
    client.global.set("user_token", response.body.token);
%}

### 2. Login as ADMIN
### Expected: 200 OK + JWT
### ------------------------------------------------------------
POST http://localhost:8080/login
Content-Type: application/json
Accept: application/json

{
  "username": "admin",
  "password": "admin123"
}

> {%
    client.global.set("admin_token", response.body.token);
%}

### ------------------------------------------------------------
### 4. ADMIN creates the demo event
### ------------------------------------------------------------
POST http://localhost:8080/events
Authorization: Bearer {{admin_token}}
Content-Type: application/json
Accept: application/json

{
  "name": "Vienna Gaming Event",
  "date": "2026-12-01T18:00:00+01:00",
  "location": "Wiener Stadthalle",
  "totalTickets": 11,
  "availableTickets": 11,
  "ticketPrice": 50.00
}

> {%
    client.global.set("event_id", response.body.id);
%}


### ------------------------------------------------------------
### 5. Get the test event
GET http://localhost:8080/events/{{event_id}}
Accept: application/json

### ------------------------------------------------------------
### 6. Purchase Ticket
### ------------------------------------------------------------
POST http://localhost:8080/events/{{event_id}}/tickets
Authorization: Bearer {{user_token}}
Accept: application/json

### ------------------------------------------------------------
### Ticket purchase WITHOUT JWT
###
### Expected: 401 Unauthorized
### ------------------------------------------------------------
POST http://localhost:8080/events/{{event_id}}/tickets
Accept: application/json


### ------------------------------------------------------------
### Get all events
### Expected: 200 OK
### ------------------------------------------------------------
GET http://localhost:8080/events
Accept: application/json


### ------------------------------------------------------------
### ADMIN deletes the event
### Expected: 204 No Content
### ------------------------------------------------------------
DELETE http://localhost:8080/events/{{event_id}}
Authorization: Bearer {{admin_token}}


### ------------------------------------------------------------
### Verify that deleted event no longer exists
### Expected: 404 Not Found
### ------------------------------------------------------------
GET http://localhost:8080/events/{{event_id}}
Accept: application/json